apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  labels:
    component: helloworld
    type: springboot
    access: external
spec:
  containers:
    - image: pmlynarczyk/helloworld:0.1-learnneat
      name: helloworld
      ports:
        - containerPort: 8080

